/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.recommend.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the RecommendEntity service. Represents a row in the &quot;rec_RecommendEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.recommend.model.impl.RecommendEntityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.recommend.model.impl.RecommendEntityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RecommendEntity
 * @see com.liferay.recommend.model.impl.RecommendEntityImpl
 * @see com.liferay.recommend.model.impl.RecommendEntityModelImpl
 * @generated
 */
@ProviderType
public interface RecommendEntityModel extends BaseModel<RecommendEntity> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a recommend entity model instance should use the {@link RecommendEntity} interface instead.
	 */

	/**
	 * Returns the primary key of this recommend entity.
	 *
	 * @return the primary key of this recommend entity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this recommend entity.
	 *
	 * @param primaryKey the primary key of this recommend entity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this recommend entity.
	 *
	 * @return the ID of this recommend entity
	 */
	public long getId();

	/**
	 * Sets the ID of this recommend entity.
	 *
	 * @param id the ID of this recommend entity
	 */
	public void setId(long id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(RecommendEntity recommendEntity);

	@Override
	public int hashCode();

	@Override
	public CacheModel<RecommendEntity> toCacheModel();

	@Override
	public RecommendEntity toEscapedModel();

	@Override
	public RecommendEntity toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}