/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.micro.maintainance.candidate.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CandidateEntry service. Represents a row in the &quot;Candidate_CandidateEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.micro.maintainance.candidate.model.impl.CandidateEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.micro.maintainance.candidate.model.impl.CandidateEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CandidateEntry
 * @see com.liferay.micro.maintainance.candidate.model.impl.CandidateEntryImpl
 * @see com.liferay.micro.maintainance.candidate.model.impl.CandidateEntryModelImpl
 * @generated
 */
@ProviderType
public interface CandidateEntryModel extends BaseModel<CandidateEntry>,
	GroupedModel, ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a candidate entry model instance should use the {@link CandidateEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this candidate entry.
	 *
	 * @return the primary key of this candidate entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this candidate entry.
	 *
	 * @param primaryKey the primary key of this candidate entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this candidate entry.
	 *
	 * @return the uuid of this candidate entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this candidate entry.
	 *
	 * @param uuid the uuid of this candidate entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the entry ID of this candidate entry.
	 *
	 * @return the entry ID of this candidate entry
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this candidate entry.
	 *
	 * @param entryId the entry ID of this candidate entry
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the group ID of this candidate entry.
	 *
	 * @return the group ID of this candidate entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this candidate entry.
	 *
	 * @param groupId the group ID of this candidate entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this candidate entry.
	 *
	 * @return the company ID of this candidate entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this candidate entry.
	 *
	 * @param companyId the company ID of this candidate entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this candidate entry.
	 *
	 * @return the user ID of this candidate entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this candidate entry.
	 *
	 * @param userId the user ID of this candidate entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this candidate entry.
	 *
	 * @return the user uuid of this candidate entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this candidate entry.
	 *
	 * @param userUuid the user uuid of this candidate entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this candidate entry.
	 *
	 * @return the user name of this candidate entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this candidate entry.
	 *
	 * @param userName the user name of this candidate entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this candidate entry.
	 *
	 * @return the create date of this candidate entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this candidate entry.
	 *
	 * @param createDate the create date of this candidate entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this candidate entry.
	 *
	 * @return the modified date of this candidate entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this candidate entry.
	 *
	 * @param modifiedDate the modified date of this candidate entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the wiki page ID of this candidate entry.
	 *
	 * @return the wiki page ID of this candidate entry
	 */
	public long getWikiPageId();

	/**
	 * Sets the wiki page ID of this candidate entry.
	 *
	 * @param wikiPageId the wiki page ID of this candidate entry
	 */
	public void setWikiPageId(long wikiPageId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CandidateEntry candidateEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CandidateEntry> toCacheModel();

	@Override
	public CandidateEntry toEscapedModel();

	@Override
	public CandidateEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}