/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.micro.maintainance.analysis.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the AnalysisUser service. Represents a row in the &quot;Analysis_AnalysisUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.micro.maintainance.analysis.model.impl.AnalysisUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.micro.maintainance.analysis.model.impl.AnalysisUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AnalysisUser
 * @see com.liferay.micro.maintainance.analysis.model.impl.AnalysisUserImpl
 * @see com.liferay.micro.maintainance.analysis.model.impl.AnalysisUserModelImpl
 * @generated
 */
@ProviderType
public interface AnalysisUserModel extends BaseModel<AnalysisUser> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a analysis user model instance should use the {@link AnalysisUser} interface instead.
	 */

	/**
	 * Returns the primary key of this analysis user.
	 *
	 * @return the primary key of this analysis user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this analysis user.
	 *
	 * @param primaryKey the primary key of this analysis user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this analysis user.
	 *
	 * @return the uuid of this analysis user
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this analysis user.
	 *
	 * @param uuid the uuid of this analysis user
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the analysis user ID of this analysis user.
	 *
	 * @return the analysis user ID of this analysis user
	 */
	public long getAnalysisUserId();

	/**
	 * Sets the analysis user ID of this analysis user.
	 *
	 * @param analysisUserId the analysis user ID of this analysis user
	 */
	public void setAnalysisUserId(long analysisUserId);

	/**
	 * Returns the analysis user uuid of this analysis user.
	 *
	 * @return the analysis user uuid of this analysis user
	 */
	public String getAnalysisUserUuid();

	/**
	 * Sets the analysis user uuid of this analysis user.
	 *
	 * @param analysisUserUuid the analysis user uuid of this analysis user
	 */
	public void setAnalysisUserUuid(String analysisUserUuid);

	/**
	 * Returns the analysis ID of this analysis user.
	 *
	 * @return the analysis ID of this analysis user
	 */
	public long getAnalysisId();

	/**
	 * Sets the analysis ID of this analysis user.
	 *
	 * @param analysisId the analysis ID of this analysis user
	 */
	public void setAnalysisId(long analysisId);

	/**
	 * Returns the user ID of this analysis user.
	 *
	 * @return the user ID of this analysis user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this analysis user.
	 *
	 * @param userId the user ID of this analysis user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this analysis user.
	 *
	 * @return the user uuid of this analysis user
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this analysis user.
	 *
	 * @param userUuid the user uuid of this analysis user
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this analysis user.
	 *
	 * @return the user name of this analysis user
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this analysis user.
	 *
	 * @param userName the user name of this analysis user
	 */
	public void setUserName(String userName);

	/**
	 * Returns the voted of this analysis user.
	 *
	 * @return the voted of this analysis user
	 */
	public int getVoted();

	/**
	 * Sets the voted of this analysis user.
	 *
	 * @param voted the voted of this analysis user
	 */
	public void setVoted(int voted);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AnalysisUser analysisUser);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AnalysisUser> toCacheModel();

	@Override
	public AnalysisUser toEscapedModel();

	@Override
	public AnalysisUser toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}