/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.micro.maintainance.analysis.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.micro.maintainance.analysis.model.AnalysisUser;
import com.liferay.micro.maintainance.analysis.service.AnalysisUserLocalService;
import com.liferay.micro.maintainance.analysis.service.persistence.AnalysisEntryPersistence;
import com.liferay.micro.maintainance.analysis.service.persistence.AnalysisUserPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the analysis user local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.micro.maintainance.analysis.service.impl.AnalysisUserLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.micro.maintainance.analysis.service.impl.AnalysisUserLocalServiceImpl
 * @see com.liferay.micro.maintainance.analysis.service.AnalysisUserLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class AnalysisUserLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements AnalysisUserLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.micro.maintainance.analysis.service.AnalysisUserLocalServiceUtil} to access the analysis user local service.
	 */

	/**
	 * Adds the analysis user to the database. Also notifies the appropriate model listeners.
	 *
	 * @param analysisUser the analysis user
	 * @return the analysis user that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AnalysisUser addAnalysisUser(AnalysisUser analysisUser) {
		analysisUser.setNew(true);

		return analysisUserPersistence.update(analysisUser);
	}

	/**
	 * Creates a new analysis user with the primary key. Does not add the analysis user to the database.
	 *
	 * @param analysisUserId the primary key for the new analysis user
	 * @return the new analysis user
	 */
	@Override
	public AnalysisUser createAnalysisUser(long analysisUserId) {
		return analysisUserPersistence.create(analysisUserId);
	}

	/**
	 * Deletes the analysis user with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param analysisUserId the primary key of the analysis user
	 * @return the analysis user that was removed
	 * @throws PortalException if a analysis user with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AnalysisUser deleteAnalysisUser(long analysisUserId)
		throws PortalException {
		return analysisUserPersistence.remove(analysisUserId);
	}

	/**
	 * Deletes the analysis user from the database. Also notifies the appropriate model listeners.
	 *
	 * @param analysisUser the analysis user
	 * @return the analysis user that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AnalysisUser deleteAnalysisUser(AnalysisUser analysisUser) {
		return analysisUserPersistence.remove(analysisUser);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(AnalysisUser.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return analysisUserPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.micro.maintainance.analysis.model.impl.AnalysisUserModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return analysisUserPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.micro.maintainance.analysis.model.impl.AnalysisUserModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return analysisUserPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return analysisUserPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return analysisUserPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public AnalysisUser fetchAnalysisUser(long analysisUserId) {
		return analysisUserPersistence.fetchByPrimaryKey(analysisUserId);
	}

	/**
	 * Returns the analysis user with the primary key.
	 *
	 * @param analysisUserId the primary key of the analysis user
	 * @return the analysis user
	 * @throws PortalException if a analysis user with the primary key could not be found
	 */
	@Override
	public AnalysisUser getAnalysisUser(long analysisUserId)
		throws PortalException {
		return analysisUserPersistence.findByPrimaryKey(analysisUserId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(analysisUserLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AnalysisUser.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("analysisUserId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(analysisUserLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AnalysisUser.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"analysisUserId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(analysisUserLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AnalysisUser.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("analysisUserId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return analysisUserLocalService.deleteAnalysisUser((AnalysisUser)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return analysisUserPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the analysis users.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.micro.maintainance.analysis.model.impl.AnalysisUserModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of analysis users
	 * @param end the upper bound of the range of analysis users (not inclusive)
	 * @return the range of analysis users
	 */
	@Override
	public List<AnalysisUser> getAnalysisUsers(int start, int end) {
		return analysisUserPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of analysis users.
	 *
	 * @return the number of analysis users
	 */
	@Override
	public int getAnalysisUsersCount() {
		return analysisUserPersistence.countAll();
	}

	/**
	 * Updates the analysis user in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param analysisUser the analysis user
	 * @return the analysis user that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AnalysisUser updateAnalysisUser(AnalysisUser analysisUser) {
		return analysisUserPersistence.update(analysisUser);
	}

	/**
	 * Returns the analysis entry local service.
	 *
	 * @return the analysis entry local service
	 */
	public com.liferay.micro.maintainance.analysis.service.AnalysisEntryLocalService getAnalysisEntryLocalService() {
		return analysisEntryLocalService;
	}

	/**
	 * Sets the analysis entry local service.
	 *
	 * @param analysisEntryLocalService the analysis entry local service
	 */
	public void setAnalysisEntryLocalService(
		com.liferay.micro.maintainance.analysis.service.AnalysisEntryLocalService analysisEntryLocalService) {
		this.analysisEntryLocalService = analysisEntryLocalService;
	}

	/**
	 * Returns the analysis entry persistence.
	 *
	 * @return the analysis entry persistence
	 */
	public AnalysisEntryPersistence getAnalysisEntryPersistence() {
		return analysisEntryPersistence;
	}

	/**
	 * Sets the analysis entry persistence.
	 *
	 * @param analysisEntryPersistence the analysis entry persistence
	 */
	public void setAnalysisEntryPersistence(
		AnalysisEntryPersistence analysisEntryPersistence) {
		this.analysisEntryPersistence = analysisEntryPersistence;
	}

	/**
	 * Returns the analysis user local service.
	 *
	 * @return the analysis user local service
	 */
	public AnalysisUserLocalService getAnalysisUserLocalService() {
		return analysisUserLocalService;
	}

	/**
	 * Sets the analysis user local service.
	 *
	 * @param analysisUserLocalService the analysis user local service
	 */
	public void setAnalysisUserLocalService(
		AnalysisUserLocalService analysisUserLocalService) {
		this.analysisUserLocalService = analysisUserLocalService;
	}

	/**
	 * Returns the analysis user persistence.
	 *
	 * @return the analysis user persistence
	 */
	public AnalysisUserPersistence getAnalysisUserPersistence() {
		return analysisUserPersistence;
	}

	/**
	 * Sets the analysis user persistence.
	 *
	 * @param analysisUserPersistence the analysis user persistence
	 */
	public void setAnalysisUserPersistence(
		AnalysisUserPersistence analysisUserPersistence) {
		this.analysisUserPersistence = analysisUserPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.micro.maintainance.analysis.model.AnalysisUser",
			analysisUserLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.micro.maintainance.analysis.model.AnalysisUser");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AnalysisUserLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AnalysisUser.class;
	}

	protected String getModelClassName() {
		return AnalysisUser.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = analysisUserPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.micro.maintainance.analysis.service.AnalysisEntryLocalService.class)
	protected com.liferay.micro.maintainance.analysis.service.AnalysisEntryLocalService analysisEntryLocalService;
	@BeanReference(type = AnalysisEntryPersistence.class)
	protected AnalysisEntryPersistence analysisEntryPersistence;
	@BeanReference(type = AnalysisUserLocalService.class)
	protected AnalysisUserLocalService analysisUserLocalService;
	@BeanReference(type = AnalysisUserPersistence.class)
	protected AnalysisUserPersistence analysisUserPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}