/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.micro.maintainance.analysis.service.base;

import com.liferay.micro.maintainance.analysis.model.AnalysisUser;
import com.liferay.micro.maintainance.analysis.service.AnalysisUserService;
import com.liferay.micro.maintainance.analysis.service.persistence.AnalysisEntryPersistence;
import com.liferay.micro.maintainance.analysis.service.persistence.AnalysisUserPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the analysis user remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.micro.maintainance.analysis.service.impl.AnalysisUserServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.micro.maintainance.analysis.service.impl.AnalysisUserServiceImpl
 * @see com.liferay.micro.maintainance.analysis.service.AnalysisUserServiceUtil
 * @generated
 */
public abstract class AnalysisUserServiceBaseImpl extends BaseServiceImpl
	implements AnalysisUserService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.micro.maintainance.analysis.service.AnalysisUserServiceUtil} to access the analysis user remote service.
	 */

	/**
	 * Returns the analysis entry local service.
	 *
	 * @return the analysis entry local service
	 */
	public com.liferay.micro.maintainance.analysis.service.AnalysisEntryLocalService getAnalysisEntryLocalService() {
		return analysisEntryLocalService;
	}

	/**
	 * Sets the analysis entry local service.
	 *
	 * @param analysisEntryLocalService the analysis entry local service
	 */
	public void setAnalysisEntryLocalService(
		com.liferay.micro.maintainance.analysis.service.AnalysisEntryLocalService analysisEntryLocalService) {
		this.analysisEntryLocalService = analysisEntryLocalService;
	}

	/**
	 * Returns the analysis entry remote service.
	 *
	 * @return the analysis entry remote service
	 */
	public com.liferay.micro.maintainance.analysis.service.AnalysisEntryService getAnalysisEntryService() {
		return analysisEntryService;
	}

	/**
	 * Sets the analysis entry remote service.
	 *
	 * @param analysisEntryService the analysis entry remote service
	 */
	public void setAnalysisEntryService(
		com.liferay.micro.maintainance.analysis.service.AnalysisEntryService analysisEntryService) {
		this.analysisEntryService = analysisEntryService;
	}

	/**
	 * Returns the analysis entry persistence.
	 *
	 * @return the analysis entry persistence
	 */
	public AnalysisEntryPersistence getAnalysisEntryPersistence() {
		return analysisEntryPersistence;
	}

	/**
	 * Sets the analysis entry persistence.
	 *
	 * @param analysisEntryPersistence the analysis entry persistence
	 */
	public void setAnalysisEntryPersistence(
		AnalysisEntryPersistence analysisEntryPersistence) {
		this.analysisEntryPersistence = analysisEntryPersistence;
	}

	/**
	 * Returns the analysis user local service.
	 *
	 * @return the analysis user local service
	 */
	public com.liferay.micro.maintainance.analysis.service.AnalysisUserLocalService getAnalysisUserLocalService() {
		return analysisUserLocalService;
	}

	/**
	 * Sets the analysis user local service.
	 *
	 * @param analysisUserLocalService the analysis user local service
	 */
	public void setAnalysisUserLocalService(
		com.liferay.micro.maintainance.analysis.service.AnalysisUserLocalService analysisUserLocalService) {
		this.analysisUserLocalService = analysisUserLocalService;
	}

	/**
	 * Returns the analysis user remote service.
	 *
	 * @return the analysis user remote service
	 */
	public AnalysisUserService getAnalysisUserService() {
		return analysisUserService;
	}

	/**
	 * Sets the analysis user remote service.
	 *
	 * @param analysisUserService the analysis user remote service
	 */
	public void setAnalysisUserService(AnalysisUserService analysisUserService) {
		this.analysisUserService = analysisUserService;
	}

	/**
	 * Returns the analysis user persistence.
	 *
	 * @return the analysis user persistence
	 */
	public AnalysisUserPersistence getAnalysisUserPersistence() {
		return analysisUserPersistence;
	}

	/**
	 * Sets the analysis user persistence.
	 *
	 * @param analysisUserPersistence the analysis user persistence
	 */
	public void setAnalysisUserPersistence(
		AnalysisUserPersistence analysisUserPersistence) {
		this.analysisUserPersistence = analysisUserPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AnalysisUserService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AnalysisUser.class;
	}

	protected String getModelClassName() {
		return AnalysisUser.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = analysisUserPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.micro.maintainance.analysis.service.AnalysisEntryLocalService.class)
	protected com.liferay.micro.maintainance.analysis.service.AnalysisEntryLocalService analysisEntryLocalService;
	@BeanReference(type = com.liferay.micro.maintainance.analysis.service.AnalysisEntryService.class)
	protected com.liferay.micro.maintainance.analysis.service.AnalysisEntryService analysisEntryService;
	@BeanReference(type = AnalysisEntryPersistence.class)
	protected AnalysisEntryPersistence analysisEntryPersistence;
	@BeanReference(type = com.liferay.micro.maintainance.analysis.service.AnalysisUserLocalService.class)
	protected com.liferay.micro.maintainance.analysis.service.AnalysisUserLocalService analysisUserLocalService;
	@BeanReference(type = AnalysisUserService.class)
	protected AnalysisUserService analysisUserService;
	@BeanReference(type = AnalysisUserPersistence.class)
	protected AnalysisUserPersistence analysisUserPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}