/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.micro.maintainance.analysis.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.micro.maintainance.analysis.model.AnalysisUser;
import com.liferay.micro.maintainance.analysis.model.AnalysisUserModel;
import com.liferay.micro.maintainance.analysis.model.AnalysisUserSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the AnalysisUser service. Represents a row in the &quot;Analysis_AnalysisUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AnalysisUserModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnalysisUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AnalysisUserImpl
 * @see AnalysisUser
 * @see AnalysisUserModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class AnalysisUserModelImpl extends BaseModelImpl<AnalysisUser>
	implements AnalysisUserModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a analysis user model instance should use the {@link AnalysisUser} interface instead.
	 */
	public static final String TABLE_NAME = "Analysis_AnalysisUser";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "analysisUserId", Types.BIGINT },
			{ "analysisId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "voted", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("analysisUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("analysisId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("voted", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table Analysis_AnalysisUser (uuid_ VARCHAR(75) null,analysisUserId LONG not null primary key,analysisId LONG,userId LONG,userName VARCHAR(75) null,voted INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table Analysis_AnalysisUser";
	public static final String ORDER_BY_JPQL = " ORDER BY analysisUser.userName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Analysis_AnalysisUser.userName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.micro.maintainance.analysis.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.micro.maintainance.analysis.model.AnalysisUser"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.micro.maintainance.analysis.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.micro.maintainance.analysis.model.AnalysisUser"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.micro.maintainance.analysis.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.com.liferay.micro.maintainance.analysis.model.AnalysisUser"),
			true);
	public static final long ANALYSISID_COLUMN_BITMASK = 1L;
	public static final long ANALYSISUSERID_COLUMN_BITMASK = 2L;
	public static final long USERID_COLUMN_BITMASK = 4L;
	public static final long USERNAME_COLUMN_BITMASK = 8L;
	public static final long UUID_COLUMN_BITMASK = 16L;
	public static final long VOTED_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AnalysisUser toModel(AnalysisUserSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AnalysisUser model = new AnalysisUserImpl();

		model.setUuid(soapModel.getUuid());
		model.setAnalysisUserId(soapModel.getAnalysisUserId());
		model.setAnalysisId(soapModel.getAnalysisId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setVoted(soapModel.getVoted());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AnalysisUser> toModels(AnalysisUserSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AnalysisUser> models = new ArrayList<AnalysisUser>(soapModels.length);

		for (AnalysisUserSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.micro.maintainance.analysis.service.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.micro.maintainance.analysis.model.AnalysisUser"));

	public AnalysisUserModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _analysisUserId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAnalysisUserId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _analysisUserId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AnalysisUser.class;
	}

	@Override
	public String getModelClassName() {
		return AnalysisUser.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("analysisUserId", getAnalysisUserId());
		attributes.put("analysisId", getAnalysisId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("voted", getVoted());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long analysisUserId = (Long)attributes.get("analysisUserId");

		if (analysisUserId != null) {
			setAnalysisUserId(analysisUserId);
		}

		Long analysisId = (Long)attributes.get("analysisId");

		if (analysisId != null) {
			setAnalysisId(analysisId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Integer voted = (Integer)attributes.get("voted");

		if (voted != null) {
			setVoted(voted);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getAnalysisUserId() {
		return _analysisUserId;
	}

	@Override
	public void setAnalysisUserId(long analysisUserId) {
		_columnBitmask |= ANALYSISUSERID_COLUMN_BITMASK;

		if (!_setOriginalAnalysisUserId) {
			_setOriginalAnalysisUserId = true;

			_originalAnalysisUserId = _analysisUserId;
		}

		_analysisUserId = analysisUserId;
	}

	@Override
	public String getAnalysisUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getAnalysisUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setAnalysisUserUuid(String analysisUserUuid) {
	}

	public long getOriginalAnalysisUserId() {
		return _originalAnalysisUserId;
	}

	@JSON
	@Override
	public long getAnalysisId() {
		return _analysisId;
	}

	@Override
	public void setAnalysisId(long analysisId) {
		_columnBitmask |= ANALYSISID_COLUMN_BITMASK;

		if (!_setOriginalAnalysisId) {
			_setOriginalAnalysisId = true;

			_originalAnalysisId = _analysisId;
		}

		_analysisId = analysisId;
	}

	public long getOriginalAnalysisId() {
		return _originalAnalysisId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_columnBitmask = -1L;

		if (_originalUserName == null) {
			_originalUserName = _userName;
		}

		_userName = userName;
	}

	public String getOriginalUserName() {
		return GetterUtil.getString(_originalUserName);
	}

	@JSON
	@Override
	public int getVoted() {
		return _voted;
	}

	@Override
	public void setVoted(int voted) {
		_columnBitmask |= VOTED_COLUMN_BITMASK;

		if (!_setOriginalVoted) {
			_setOriginalVoted = true;

			_originalVoted = _voted;
		}

		_voted = voted;
	}

	public int getOriginalVoted() {
		return _originalVoted;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			AnalysisUser.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AnalysisUser toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AnalysisUser)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AnalysisUserImpl analysisUserImpl = new AnalysisUserImpl();

		analysisUserImpl.setUuid(getUuid());
		analysisUserImpl.setAnalysisUserId(getAnalysisUserId());
		analysisUserImpl.setAnalysisId(getAnalysisId());
		analysisUserImpl.setUserId(getUserId());
		analysisUserImpl.setUserName(getUserName());
		analysisUserImpl.setVoted(getVoted());

		analysisUserImpl.resetOriginalValues();

		return analysisUserImpl;
	}

	@Override
	public int compareTo(AnalysisUser analysisUser) {
		int value = 0;

		value = getUserName().compareTo(analysisUser.getUserName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AnalysisUser)) {
			return false;
		}

		AnalysisUser analysisUser = (AnalysisUser)obj;

		long primaryKey = analysisUser.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		AnalysisUserModelImpl analysisUserModelImpl = this;

		analysisUserModelImpl._originalUuid = analysisUserModelImpl._uuid;

		analysisUserModelImpl._originalAnalysisUserId = analysisUserModelImpl._analysisUserId;

		analysisUserModelImpl._setOriginalAnalysisUserId = false;

		analysisUserModelImpl._originalAnalysisId = analysisUserModelImpl._analysisId;

		analysisUserModelImpl._setOriginalAnalysisId = false;

		analysisUserModelImpl._originalUserId = analysisUserModelImpl._userId;

		analysisUserModelImpl._setOriginalUserId = false;

		analysisUserModelImpl._originalUserName = analysisUserModelImpl._userName;

		analysisUserModelImpl._originalVoted = analysisUserModelImpl._voted;

		analysisUserModelImpl._setOriginalVoted = false;

		analysisUserModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AnalysisUser> toCacheModel() {
		AnalysisUserCacheModel analysisUserCacheModel = new AnalysisUserCacheModel();

		analysisUserCacheModel.uuid = getUuid();

		String uuid = analysisUserCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			analysisUserCacheModel.uuid = null;
		}

		analysisUserCacheModel.analysisUserId = getAnalysisUserId();

		analysisUserCacheModel.analysisId = getAnalysisId();

		analysisUserCacheModel.userId = getUserId();

		analysisUserCacheModel.userName = getUserName();

		String userName = analysisUserCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			analysisUserCacheModel.userName = null;
		}

		analysisUserCacheModel.voted = getVoted();

		return analysisUserCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", analysisUserId=");
		sb.append(getAnalysisUserId());
		sb.append(", analysisId=");
		sb.append(getAnalysisId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", voted=");
		sb.append(getVoted());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.liferay.micro.maintainance.analysis.model.AnalysisUser");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>analysisUserId</column-name><column-value><![CDATA[");
		sb.append(getAnalysisUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>analysisId</column-name><column-value><![CDATA[");
		sb.append(getAnalysisId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>voted</column-name><column-value><![CDATA[");
		sb.append(getVoted());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AnalysisUser.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AnalysisUser.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _analysisUserId;
	private long _originalAnalysisUserId;
	private boolean _setOriginalAnalysisUserId;
	private long _analysisId;
	private long _originalAnalysisId;
	private boolean _setOriginalAnalysisId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private String _originalUserName;
	private int _voted;
	private int _originalVoted;
	private boolean _setOriginalVoted;
	private long _columnBitmask;
	private AnalysisUser _escapedModel;
}