/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.micro.maintainance.task.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.micro.maintainance.task.model.TaskEntry;
import com.liferay.micro.maintainance.task.service.TaskEntryLocalServiceUtil;

/**
 * The extended model base implementation for the TaskEntry service. Represents a row in the &quot;Task_TaskEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TaskEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TaskEntryImpl
 * @see TaskEntry
 * @generated
 */
@ProviderType
public abstract class TaskEntryBaseImpl extends TaskEntryModelImpl
	implements TaskEntry {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a task entry model instance should use the {@link TaskEntry} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TaskEntryLocalServiceUtil.addTaskEntry(this);
		}
		else {
			TaskEntryLocalServiceUtil.updateTaskEntry(this);
		}
	}
}