/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.grow.gamification.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BadgeType service. Represents a row in the &quot;gamification_BadgeType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.grow.gamification.model.impl.BadgeTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.grow.gamification.model.impl.BadgeTypeImpl}.
 * </p>
 *
 * @author Vilmos Papp
 * @see BadgeType
 * @see com.liferay.grow.gamification.model.impl.BadgeTypeImpl
 * @see com.liferay.grow.gamification.model.impl.BadgeTypeModelImpl
 * @generated
 */
@ProviderType
public interface BadgeTypeModel extends BaseModel<BadgeType>, GroupedModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a badge type model instance should use the {@link BadgeType} interface instead.
	 */

	/**
	 * Returns the primary key of this badge type.
	 *
	 * @return the primary key of this badge type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this badge type.
	 *
	 * @param primaryKey the primary key of this badge type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the badge type ID of this badge type.
	 *
	 * @return the badge type ID of this badge type
	 */
	public long getBadgeTypeId();

	/**
	 * Sets the badge type ID of this badge type.
	 *
	 * @param badgeTypeId the badge type ID of this badge type
	 */
	public void setBadgeTypeId(long badgeTypeId);

	/**
	 * Returns the group ID of this badge type.
	 *
	 * @return the group ID of this badge type
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this badge type.
	 *
	 * @param groupId the group ID of this badge type
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this badge type.
	 *
	 * @return the company ID of this badge type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this badge type.
	 *
	 * @param companyId the company ID of this badge type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this badge type.
	 *
	 * @return the user ID of this badge type
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this badge type.
	 *
	 * @param userId the user ID of this badge type
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this badge type.
	 *
	 * @return the user uuid of this badge type
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this badge type.
	 *
	 * @param userUuid the user uuid of this badge type
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this badge type.
	 *
	 * @return the user name of this badge type
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this badge type.
	 *
	 * @param userName the user name of this badge type
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this badge type.
	 *
	 * @return the create date of this badge type
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this badge type.
	 *
	 * @param createDate the create date of this badge type
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this badge type.
	 *
	 * @return the modified date of this badge type
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this badge type.
	 *
	 * @param modifiedDate the modified date of this badge type
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the type of this badge type.
	 *
	 * @return the type of this badge type
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this badge type.
	 *
	 * @param type the type of this badge type
	 */
	public void setType(String type);

	/**
	 * Returns the assignable from of this badge type.
	 *
	 * @return the assignable from of this badge type
	 */
	public Date getAssignableFrom();

	/**
	 * Sets the assignable from of this badge type.
	 *
	 * @param assignableFrom the assignable from of this badge type
	 */
	public void setAssignableFrom(Date assignableFrom);

	/**
	 * Returns the assignable to of this badge type.
	 *
	 * @return the assignable to of this badge type
	 */
	public Date getAssignableTo();

	/**
	 * Sets the assignable to of this badge type.
	 *
	 * @param assignableTo the assignable to of this badge type
	 */
	public void setAssignableTo(Date assignableTo);

	/**
	 * Returns the file entry ID of this badge type.
	 *
	 * @return the file entry ID of this badge type
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this badge type.
	 *
	 * @param fileEntryId the file entry ID of this badge type
	 */
	public void setFileEntryId(long fileEntryId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BadgeType badgeType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BadgeType> toCacheModel();

	@Override
	public BadgeType toEscapedModel();

	@Override
	public BadgeType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}