/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.grow.gamification.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Badge service. Represents a row in the &quot;gamification_Badge&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.grow.gamification.model.impl.BadgeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.grow.gamification.model.impl.BadgeImpl}.
 * </p>
 *
 * @author Vilmos Papp
 * @see Badge
 * @see com.liferay.grow.gamification.model.impl.BadgeImpl
 * @see com.liferay.grow.gamification.model.impl.BadgeModelImpl
 * @generated
 */
@ProviderType
public interface BadgeModel extends BaseModel<Badge>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a badge model instance should use the {@link Badge} interface instead.
	 */

	/**
	 * Returns the primary key of this badge.
	 *
	 * @return the primary key of this badge
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this badge.
	 *
	 * @param primaryKey the primary key of this badge
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this badge.
	 *
	 * @return the uuid of this badge
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this badge.
	 *
	 * @param uuid the uuid of this badge
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the badge ID of this badge.
	 *
	 * @return the badge ID of this badge
	 */
	public long getBadgeId();

	/**
	 * Sets the badge ID of this badge.
	 *
	 * @param badgeId the badge ID of this badge
	 */
	public void setBadgeId(long badgeId);

	/**
	 * Returns the group ID of this badge.
	 *
	 * @return the group ID of this badge
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this badge.
	 *
	 * @param groupId the group ID of this badge
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this badge.
	 *
	 * @return the company ID of this badge
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this badge.
	 *
	 * @param companyId the company ID of this badge
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this badge.
	 *
	 * @return the user ID of this badge
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this badge.
	 *
	 * @param userId the user ID of this badge
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this badge.
	 *
	 * @return the user uuid of this badge
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this badge.
	 *
	 * @param userUuid the user uuid of this badge
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this badge.
	 *
	 * @return the user name of this badge
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this badge.
	 *
	 * @param userName the user name of this badge
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this badge.
	 *
	 * @return the create date of this badge
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this badge.
	 *
	 * @param createDate the create date of this badge
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the badge type ID of this badge.
	 *
	 * @return the badge type ID of this badge
	 */
	public long getBadgeTypeId();

	/**
	 * Sets the badge type ID of this badge.
	 *
	 * @param badgeTypeId the badge type ID of this badge
	 */
	public void setBadgeTypeId(long badgeTypeId);

	/**
	 * Returns the to user ID of this badge.
	 *
	 * @return the to user ID of this badge
	 */
	public long getToUserId();

	/**
	 * Sets the to user ID of this badge.
	 *
	 * @param toUserId the to user ID of this badge
	 */
	public void setToUserId(long toUserId);

	/**
	 * Returns the to user uuid of this badge.
	 *
	 * @return the to user uuid of this badge
	 */
	public String getToUserUuid();

	/**
	 * Sets the to user uuid of this badge.
	 *
	 * @param toUserUuid the to user uuid of this badge
	 */
	public void setToUserUuid(String toUserUuid);

	/**
	 * Returns the description of this badge.
	 *
	 * @return the description of this badge
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this badge.
	 *
	 * @param description the description of this badge
	 */
	public void setDescription(String description);

	/**
	 * Returns the assigned date ID of this badge.
	 *
	 * @return the assigned date ID of this badge
	 */
	public long getAssignedDateId();

	/**
	 * Sets the assigned date ID of this badge.
	 *
	 * @param assignedDateId the assigned date ID of this badge
	 */
	public void setAssignedDateId(long assignedDateId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Badge badge);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Badge> toCacheModel();

	@Override
	public Badge toEscapedModel();

	@Override
	public Badge toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}