/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.grow.gamification.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the LDate service. Represents a row in the &quot;gamification_LDate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.grow.gamification.model.impl.LDateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.grow.gamification.model.impl.LDateImpl}.
 * </p>
 *
 * @author Vilmos Papp
 * @see LDate
 * @see com.liferay.grow.gamification.model.impl.LDateImpl
 * @see com.liferay.grow.gamification.model.impl.LDateModelImpl
 * @generated
 */
@ProviderType
public interface LDateModel extends BaseModel<LDate> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a l date model instance should use the {@link LDate} interface instead.
	 */

	/**
	 * Returns the primary key of this l date.
	 *
	 * @return the primary key of this l date
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this l date.
	 *
	 * @param primaryKey the primary key of this l date
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the date ID of this l date.
	 *
	 * @return the date ID of this l date
	 */
	public long getDateId();

	/**
	 * Sets the date ID of this l date.
	 *
	 * @param dateId the date ID of this l date
	 */
	public void setDateId(long dateId);

	/**
	 * Returns the year of this l date.
	 *
	 * @return the year of this l date
	 */
	public int getYear();

	/**
	 * Sets the year of this l date.
	 *
	 * @param year the year of this l date
	 */
	public void setYear(int year);

	/**
	 * Returns the month of this l date.
	 *
	 * @return the month of this l date
	 */
	public int getMonth();

	/**
	 * Sets the month of this l date.
	 *
	 * @param month the month of this l date
	 */
	public void setMonth(int month);

	/**
	 * Returns the month name of this l date.
	 *
	 * @return the month name of this l date
	 */
	@AutoEscape
	public String getMonthName();

	/**
	 * Sets the month name of this l date.
	 *
	 * @param monthName the month name of this l date
	 */
	public void setMonthName(String monthName);

	/**
	 * Returns the day of this l date.
	 *
	 * @return the day of this l date
	 */
	public int getDay();

	/**
	 * Sets the day of this l date.
	 *
	 * @param day the day of this l date
	 */
	public void setDay(int day);

	/**
	 * Returns the day of year of this l date.
	 *
	 * @return the day of year of this l date
	 */
	public int getDayOfYear();

	/**
	 * Sets the day of year of this l date.
	 *
	 * @param dayOfYear the day of year of this l date
	 */
	public void setDayOfYear(int dayOfYear);

	/**
	 * Returns the week of this l date.
	 *
	 * @return the week of this l date
	 */
	public int getWeek();

	/**
	 * Sets the week of this l date.
	 *
	 * @param week the week of this l date
	 */
	public void setWeek(int week);

	/**
	 * Returns the week day of this l date.
	 *
	 * @return the week day of this l date
	 */
	@AutoEscape
	public String getWeekDay();

	/**
	 * Sets the week day of this l date.
	 *
	 * @param weekDay the week day of this l date
	 */
	public void setWeekDay(String weekDay);

	/**
	 * Returns the quarter of this l date.
	 *
	 * @return the quarter of this l date
	 */
	@AutoEscape
	public String getQuarter();

	/**
	 * Sets the quarter of this l date.
	 *
	 * @param quarter the quarter of this l date
	 */
	public void setQuarter(String quarter);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LDate lDate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LDate> toCacheModel();

	@Override
	public LDate toEscapedModel();

	@Override
	public LDate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}